
INSERT INTO ADDRESS(ADDRESSES_LIST, APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','24','BLOC 22','OTOPENI','ROMANIA','1A','ETAJ 10','44','21','ILFOV','STRADA MONNET','001144');
INSERT INTO ADDRESS(ADDRESSES_LIST,APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','44','BLOC 1','OTOPENI','ROMANIA','1BA','ETAJ 1','44','21','ILFOV','STRADA JEAN MONNET','001144');
INSERT INTO ADDRESS(ADDRESSES_LIST,APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','13','BLOC 23','IASI','ROMANIA','1B','ETAJ 1','44','21','IASI','SPLAIUL UNIRII','001133');
INSERT INTO ADDRESS(ADDRESSES_LIST,APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','19','VILA 2','BUVURESTI','ROMANIA','1B','VILA','19','21','SECTOR 1','BULEVARDUL PRIMAVERII','001144');
INSERT INTO ADDRESS(ADDRESSES_LIST,APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','1','CASA 1','BUCURESTI','ROMANIA','233B','ETAJ 1','44','21','SECTOR 4','RANDUNELELOR','001184');

SELECT * FROM ADDRESS;

INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('1','100X200X10','1KG');
INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('2','500X200X20','2KG');
INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('3','600X200X30','3KG');
INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('4','2300X200x40','4KG');
INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('5','9900X200X50','5KG');

SELECT * FROM CARACTERISTICS;

INSERT INTO FAVORITE(CLIENT_ID) VALUES('1');
INSERT INTO FAVORITE(CLIENT_ID) VALUES('2');
INSERT INTO FAVORITE(CLIENT_ID) VALUES('3');
INSERT INTO FAVORITE(CLIENT_ID) VALUES('4');

SELECT * FROM FAVORITE;

INSERT INTO PRODUCT(PRICE, CATEGORY_ID, STOCK, BRAND, DESCRIPTION, NAME, SMALL_DESCRIPTION) VALUES('1000','1','28','APPLE','CEL MAI IPHONE','IPHONE 31','BLABLA');
INSERT INTO PRODUCT(PRICE, CATEGORY_ID, STOCK, BRAND, DESCRIPTION, NAME, SMALL_DESCRIPTION) VALUES('2569','1','10','SAMSUNG','CEL MAI NOU','S7','LALALA');
INSERT INTO PRODUCT(PRICE, CATEGORY_ID, STOCK, BRAND, DESCRIPTION, NAME, SMALL_DESCRIPTION) VALUES('2','1','300','LIVADA MERILOR','MERE VERZI FARA PETE CALITATEA 1','MAR VERDE','MAR VERDE');
INSERT INTO PRODUCT(PRICE, CATEGORY_ID, STOCK, BRAND, DESCRIPTION, NAME, SMALL_DESCRIPTION) VALUES('2500','1','COMODA','MOBEXPERT','COMODA DIN LEMN DE CIRES','COMODA TOKYO','COMODA ROSIATICA');

SELECT * FROM PRODUCT;

INSERT INTO COURIER(FIRST_NAME, LAST_NAME, PHONE) VALUES('GEORGE','CURIERUL','077373711');
INSERT INTO COURIER(FIRST_NAME, LAST_NAME, PHONE) VALUES('IRINA','EREMIA','077373799');
INSERT INTO COURIER(FIRST_NAME, LAST_NAME, PHONE) VALUES('VASILE','TITULESCU','077373755');

SELECT * FROM COURIER;

INSERT INTO ORDERS(CART_ID, DATE, STATUS) VALUES('1','12.10.2023','PENDING');
INSERT INTO ORDERS(CART_ID, DATE, STATUS) VALUES('1','23.05.2022','DELIVERED');
INSERT INTO ORDERS(CART_ID, DATE, STATUS) VALUES('1','06.10.2007','RETURNED');

SELECT * FROM ORDERS;

INSERT INTO SPECIFICATION(SPECIFICATIONS_LIST, NAME, SPECIFICATION_VALUE) VALUES('PHONE_SPEC','DIAGONALA ECRAN','3INCH');
INSERT INTO SPECIFICATION(SPECIFICATIONS_LIST, NAME, SPECIFICATION_VALUE) VALUES('FRUCTE_SPEC','ORIGINE','AFRICA DE SUD');
INSERT INTO SPECIFICATION(SPECIFICATIONS_LIST, NAME, SPECIFICATION_VALUE) VALUES('PHONE_SPEC','SISTEM DE OPERARE','IOS');

SELECT * FROM SPECIFICATION;

INSERT INTO SUBCATEGORY(SUBCATEGORY_LIST, NAME) VALUES('SMART_PHONES','SMARTPHONE');
INSERT INTO SUBCATEGORY(SUBCATEGORY_LIST, NAME) VALUES('QWERTY_PHONES','QPHONE');
INSERT INTO SUBCATEGORY(SUBCATEGORY_LIST, NAME) VALUES('EXOTIC_FRUITS','SMARTPHONE');

SELECT * FROM SUBCATEGORY;

INSERT INTO WALLET(WALLETS_LIST, CARD_NO, CVV, EXPIRATION_DATE, NAME_ON_CARD) VALUES('1','500100','123','12/10','EMIR ZURLAN');
INSERT INTO WALLET(WALLETS_LIST, CARD_NO, CVV, EXPIRATION_DATE, NAME_ON_CARD) VALUES('1','644587','123','13/12','ZIV JOHN');
INSERT INTO WALLET(WALLETS_LIST, CARD_NO, CVV, EXPIRATION_DATE, NAME_ON_CARD) VALUES('2','500100','321','09/26','GIGI HADID');

SELECT * FROM WALLET;

INSERT INTO CLIENT(CART_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE) VALUES('1','EMIR@gmail.com','EMIR','ZURLAN','07378999');
INSERT INTO CLIENT(CART_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE) VALUES('2','ZIV@gmail.com','EMIR','ZURLAN','58977732');
INSERT INTO CLIENT(CART_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE) VALUES('3','GIGI@gmail.com','GIGI','HADID','0123558');

SELECT * FROM CLIENT;

INSERT INTO CART_ITEM(AMOUNT, TOTAL_PER_ITEM_TYPE, PRODUCT_ID) VALUES('10','23566','1');
INSERT INTO CART_ITEM(AMOUNT, TOTAL_PER_ITEM_TYPE, PRODUCT_ID) VALUES('20','23566','2');
INSERT INTO CART_ITEM(AMOUNT, TOTAL_PER_ITEM_TYPE, PRODUCT_ID) VALUES('30','23566','3');
INSERT INTO CART_ITEM(AMOUNT, TOTAL_PER_ITEM_TYPE, PRODUCT_ID) VALUES('40','23566','4');

SELECT * FROM CART_ITEM;

INSERT INTO CART(TOTAL) VALUES('100');
INSERT INTO CART(TOTAL) VALUES('200');

SELECT * FROM CART;

INSERT INTO CATEGORY(NAME) VALUES('PHONES');
INSERT INTO CATEGORY(NAME) VALUES('FRUITS');

SELECT * FROM CATEGORY;










