
INSERT INTO ADDRESS(ADDRESSES_LIST, APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','24','BLOC 22','OTOPENI','ROMANIA','1A','ETAJ 10','44','21','ILFOV','STRADA MONNET','001144');
INSERT INTO ADDRESS(ADDRESSES_LIST,APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','44','BLOC 1','OTOPENI','ROMANIA','1BA','ETAJ 1','44','21','ILFOV','STRADA JEAN MONNET','001144');
INSERT INTO ADDRESS(ADDRESSES_LIST,APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','13','BLOC 23','IASI','ROMANIA','1B','ETAJ 1','44','21','IASI','SPLAIUL UNIRII','001133');
INSERT INTO ADDRESS(ADDRESSES_LIST,APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','19','VILA 2','BUVURESTI','ROMANIA','1B','VILA','19','21','SECTOR 1','BULEVARDUL PRIMAVERII','001144');
INSERT INTO ADDRESS(ADDRESSES_LIST,APARTAMENT, BUILDING, CITY, COUNTRY, ENTRY_NO, FLOOR, INTERPHONE, NUMBER, STATE_COUNTY_SECTOR, STREET, ZIP) VALUES ('1','1','CASA 1','BUCURESTI','ROMANIA','233B','ETAJ 1','44','21','SECTOR 4','RANDUNELELOR','001184');

SELECT * FROM ADDRESS;

INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('1','100X200X10','1KG');
INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('2','500X200X20','2KG');
INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('3','600X200X30','3KG');
INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('4','2300X200x40','4KG');
INSERT INTO CARACTERISTICS(PRODUCT_ID, DIMENSSIONS, WEIGHT) VALUES ('5','9900X200X50','5KG');

SELECT * FROM CARACTERISTICS;

INSERT INTO FAVORITE(CLIENT_ID) VALUES('1');
INSERT INTO FAVORITE(CLIENT_ID) VALUES('2');
INSERT INTO FAVORITE(CLIENT_ID) VALUES('3');
INSERT INTO FAVORITE(CLIENT_ID) VALUES('4');

SELECT * FROM FAVORITE;

INSERT INTO PRODUCT(PRICE, CATEGORY_ID, STOCK, BRAND, DESCRIPTION, NAME, SMALL_DESCRIPTION) VALUES('1000','1','28','APPLE','CEL MAI IPHONE','IPHONE 31','BLABLA');
INSERT INTO PRODUCT(PRICE, CATEGORY_ID, STOCK, BRAND, DESCRIPTION, NAME, SMALL_DESCRIPTION) VALUES('2569','1','10','SAMSUNG','CEL MAI NOU','S7','LALALA');
INSERT INTO PRODUCT(PRICE, CATEGORY_ID, STOCK, BRAND, DESCRIPTION, NAME, SMALL_DESCRIPTION) VALUES('2','1','300','LIVADA MERILOR','MERE VERZI FARA PETE CALITATEA 1','MAR VERDE','MAR VERDE');
INSERT INTO PRODUCT(PRICE, CATEGORY_ID, STOCK, BRAND, DESCRIPTION, NAME, SMALL_DESCRIPTION) VALUES('2500','1','COMODA','MOBEXPERT','COMODA DIN LEMN DE CIRES','COMODA TOKYO','COMODA ROSIATICA');

SELECT * FROM PRODUCT;

INSERT INTO COURIER(FIRST_NAME, LAST_NAME, PHONE) VALUES('GEORGE','CURIERUL','077373711');
INSERT INTO COURIER(FIRST_NAME, LAST_NAME, PHONE) VALUES('IRINA','EREMIA','077373799');
INSERT INTO COURIER(FIRST_NAME, LAST_NAME, PHONE) VALUES('VASILE','TITULESCU','077373755');

SELECT * FROM COURIER;

INSERT INTO ORDERS(CART_ID, DATE, STATUS) VALUES('1','12.10.2023','PENDING');
INSERT INTO ORDERS(CART_ID, DATE, STATUS) VALUES('1','23.05.2022','DELIVERED');
INSERT INTO ORDERS(CART_ID, DATE, STATUS) VALUES('1','06.10.2007','RETURNED');

SELECT * FROM ORDERS;

INSERT INTO SPECIFICATION(SPECIFICATIONS_LIST, NAME, SPECIFICATION_VALUE) VALUES('PHONE_SPEC','DIAGONALA ECRAN','3INCH');
INSERT INTO SPECIFICATION(SPECIFICATIONS_LIST, NAME, SPECIFICATION_VALUE) VALUES('FRUCTE_SPEC','ORIGINE','AFRICA DE SUD');
INSERT INTO SPECIFICATION(SPECIFICATIONS_LIST, NAME, SPECIFICATION_VALUE) VALUES('PHONE_SPEC','SISTEM DE OPERARE','IOS');

SELECT * FROM SPECIFICATION;

INSERT INTO SUBCATEGORY(SUBCATEGORY_LIST, NAME) VALUES('SMART_PHONES','SMARTPHONE');
INSERT INTO SUBCATEGORY(SUBCATEGORY_LIST, NAME) VALUES('QWERTY_PHONES','QPHONE');
INSERT INTO SUBCATEGORY(SUBCATEGORY_LIST, NAME) VALUES('EXOTIC_FRUITS','SMARTPHONE');

SELECT * FROM SUBCATEGORY;

INSERT INTO WALLET(WALLETS_LIST, CARD_NO, CVV, EXPIRATION_DATE, NAME_ON_CARD) VALUES('1','500100','123','12/10','EMIR ZURLAN');
INSERT INTO WALLET(WALLETS_LIST, CARD_NO, CVV, EXPIRATION_DATE, NAME_ON_CARD) VALUES('1','644587','123','13/12','ZIV JOHN');
INSERT INTO WALLET(WALLETS_LIST, CARD_NO, CVV, EXPIRATION_DATE, NAME_ON_CARD) VALUES('2','500100','321','09/26','GIGI HADID');

SELECT * FROM WALLET;

INSERT INTO CLIENT(CART_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE) VALUES('1','EMIR@gmail.com','EMIR','ZURLAN','07378999');
INSERT INTO CLIENT(CART_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE) VALUES('2','ZIV@gmail.com','EMIR','ZURLAN','58977732');
INSERT INTO CLIENT(CART_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE) VALUES('3','GIGI@gmail.com','GIGI','HADID','0123558');

SELECT * FROM CLIENT;

INSERT INTO CART_ITEM(AMOUNT, TOTAL_PER_ITEM_TYPE, PRODUCT_ID) VALUES('10','23566','1');
INSERT INTO CART_ITEM(AMOUNT, TOTAL_PER_ITEM_TYPE, PRODUCT_ID) VALUES('20','23566','2');
INSERT INTO CART_ITEM(AMOUNT, TOTAL_PER_ITEM_TYPE, PRODUCT_ID) VALUES('30','23566','3');
INSERT INTO CART_ITEM(AMOUNT, TOTAL_PER_ITEM_TYPE, PRODUCT_ID) VALUES('40','23566','4');

SELECT * FROM CART_ITEM;

INSERT INTO CART(TOTAL) VALUES('100');
INSERT INTO CART(TOTAL) VALUES('200');

SELECT * FROM CART;

INSERT INTO CATEGORY(NAME) VALUES('PHONES');
INSERT INTO CATEGORY(NAME) VALUES('FRUITS');

SELECT * FROM CATEGORY;


//FOR TESTING
    public void productsAvailable(){
        Product product1 = new Product();
        product1.setName("Iphone 23");
        product1.setBrand("Apple");
        product1.setDescription("Cel mai nou Iphone cu 32GB RAM");
        product1.setSmallDescription("32GB RAM, Oled");
        product1.setPrice(BigDecimal.valueOf(5000));

        Product product2 = new Product();
        product2.setName("S99");
        product2.setBrand("Samsung");
        product2.setDescription("Cel performant televizor cu tehnologia blabla.");
        product2.setSmallDescription("64GB RAM, Oled, blabla");
        product2.setPrice(BigDecimal.valueOf(11000));

        Product product3 = new Product();
        product3.setName("Paracetamol");
        product3.setBrand("DaciaFarm");
        product3.setDescription("Medicamentul potrivit pentru dureri de cap si altele");
        product3.setSmallDescription("Paracetamol cu vitamina X");
        product3.setPrice(BigDecimal.valueOf(15));

        Product product4 = new Product();
        product4.setName("Mar Rosu");
        product4.setBrand("Livada rosie");
        product4.setDescription("Mere Bio crescute in livada din zona 2");
        product4.setSmallDescription("Mar rosu BIO");
        product4.setPrice(BigDecimal.valueOf(2));

        Product product5 = new Product();
        product5.setName("Gin Boe Violet Fantasy");
        product5.setBrand("Boe");
        product5.setDescription("Cel mai aromat gin venit direct din UK");
        product5.setSmallDescription("Boe Violet");
        product5.setPrice(BigDecimal.valueOf(250));

        Product product6 = new Product();
        product6.setName("Prosecco");
        product6.setBrand("MOET");
        product6.setDescription("Prosecco stors si fermentat din struguri virgini din Franta si Italia");
        product6.setSmallDescription("Prosecco France&Italy");
        product6.setPrice(BigDecimal.valueOf(900));

        productRepository.save(product1);
        productRepository.save(product2);
        productRepository.save(product3);
        productRepository.save(product4);
        productRepository.save(product5);
        productRepository.save(product6);
}







