INSERT INTO CARACTERISTIC(DIMENSSIONS,WEIGHT) VALUES(100,100);
    INSERT INTO CARACTERISTIC(DIMENSSIONS,WEIGHT) VALUES(50,100);
INSERT INTO PRODUCT(CARACTERISTIC_ID, CATEGORY_ID, NAME, BRAND, DESCRIPTION, PRICE) VALUES(1,1,'Telefon','Samsung','Nou','1000');
INSERT INTO PRODUCT(CARACTERISTIC_ID, CATEGORY_ID, NAME, BRAND, DESCRIPTION, PRICE) VALUES(2,1,'Telefon','Samsung','Nou','1000');
SELECT * FROM PRODUCT;